### ISSUE TITLE
:RubyRun command with transparent background

### ISSUE THREAD

**Issue by ghost** [vinibispo/ruby.nvim#8]
When testing the :RubyRun % command

The following behavior appeared with the transparent background

![plugin](https://user-images.githubusercontent.com/50991478/130852018-27cdc4e0-9063-497e-8281-1c2786b286aa.gif)

my init.vim
```
call plug#begin()
Plug 'altercation/vim-colors-solarized'
Plug 'scrooloose/nerdtree'
Plug 'nvim-lua/plenary.nvim'
Plug 'vinibispo/ruby.nvim', {'for': 'ruby'}
call plug#end()

" Indention Options
set autoindent
filetype plugin on
filetype indent off
set smartindent
set expandtab
set shiftround
set shiftwidth=2
set smarttab
set tabstop=2

" Search Options
set hlsearch
set ignorecase
set incsearch
set smartcase

" Text Rendering Options
set display+=lastline
set encoding=utf-8
set linebreak
syntax enable
set wrap

" User Interface Options
set laststatus=2
set ruler
set wildmenu
set tabpagemax=50
colorscheme solarized 
set background=dark
set cursorline
set number
set relativenumber
set nornu
set noerrorbells
set visualbell
set mouse=a
set title
set clipboard=unnamed,unnamedplus

" Code Folding Options
set foldmethod=indent
set foldnestmax=3
set nofoldenable

" Miscellaneous Options
set autoread
set backspace=indent,eol,start
set confirm
set hidden
set history=1000
set nomodeline
set spell

" Start NERDTree and leave the cursor in it.
autocmd VimEnter * NERDTree
let NERDTreeShowHidden=1
map <C-n> :NERDTreeToggle<CR>
```

Terminal: Iterm2 and neovim both using the solarized dark color scheme.

**Comment by vinibispo** [comment]
Right, what do you think about this @cuducos ?

**Comment by cuducos** [comment]
I'm sorry, but I couldn't reproduce this error.

To avoid messing up my local environment, I tested it in a container. I'll share a step-by-step so you can help me to spot any difference:

### The container

This is the `Dockerfile`:

```dockerfile
FROM ruby:2.7.2-slim
RUN  apt update && \
     apt install -y curl git && \
     curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage && \
     chmod u+x nvim.appimage && \
     ./nvim.appimage --appimage-extract && \
     mkdir -p ~/.config/nvim && \
     touch ~/.config/nvim/init.vim && \
     curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && \
     echo "puts 'Hello, Ruby!'" > app.rb
CMD ./squashfs-root/AppRun
```

It basically installs `curl` and Git with the APT package manager, then downloads and extracts Neovim from its app image, install Plug (since that's the plugin manager @jp7webdesign uses in their `init.vim`). It also creates a simple _hello world_ in Ruby and Neovim configuration directory and files.

Then I build and run it:

```console
$ docker build -t ruby_nvim .
$ docker run -it ruby_nvim
```

### Setting up Neovim

Running the container will open its Neovim, in which I run `:e ~/.config/nvim/init.vim`, pasted @jp7webdesign's `init.vim` and saves it with `:w`.

Then I __source__ it, install plugins, closes the plugin installation buffer when it is done, and source it again (not sure if necessary):

```
:source %
:PlugInstall
:bw
:source %
```

### Trying to reproduce the bug

```
:e app.rb
:RubyRun %
```

![image](https://user-images.githubusercontent.com/4732915/133291801-cc3fbf0b-8b05-475b-b6e1-9601c1694fd6.png)
